### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by aaronwong1989** [aaronwong1989/blind-watermark#1]
运行时报错
```
2018-11-28 19:41:30.394  INFO 18360 --- [           main] c.c.z.b.BlindWatermarkApplication        : opencv load success ! 
[  1,   0,   0;
   0,   1,   0;
   0,   0,   1]

java.lang.UnsatisfiedLinkError: no jniBlindWatermarkApplication in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1258)
	at org.bytedeco.javacpp.Loader.load(Loader.java:999)
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at cn.com.zybank.blindwatermark.BlindWatermarkApplication.main(BlindWatermarkApplication.java:29)
Exception in thread "main" java.lang.NullPointerException
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:374)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:356)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:323)
	at cn.com.zybank.blindwatermark.BlindWatermarkApplication.main(BlindWatermarkApplication.java:32)
```

通过代码看应该时初始化成功了，但还是报错

**Comment by aaronwong1989** [comment]
见readme说明
